NAME = "🔲 Signature Nodes"

IMAGE_CAT = f"{NAME}/🖼️ Image"
MASK_CAT = f"{NAME}/🎭 Mask"
TEXT_CAT = f"{NAME}/🔤 Text"
NUMBERS_CAT = f"{NAME}/🔢 Numbers"
TRANSFORM_CAT = f"{NAME}/🔄 Transforms"
PRIMITIVES_CAT = f"{NAME}/🧱 Primitives"
MODELS_CAT = f"{NAME}/🤖 Models"
LOGIC_CAT = f"{NAME}/🧠 Logic"
FILE_CAT = f"{NAME}/📁 File"
AUGMENTATION_CAT = f"{NAME}/🔧 Others/🔀 Augmentations"
PLATFROM_IO_CAT = f"{NAME}/🔧 Others/🔌 Platform IO"
DATA_CAT = f"{NAME}/🔧 Others/📊 Data"
LORA_CAT = f"{NAME}/🔧 Others/🧬 Loras"
UTILS_CAT = f"{NAME}/🔧 Others/🛠️ Utils"
