NAME = "🔲 Signature Nodes"

IMAGE_CAT = f"{NAME}/🖼️ Image"
MASK_CAT = f"{NAME}/🎭 Mask"
NUMBERS_CAT = f"{NAME}/🔢 Numbers"
TRANSFORM_CAT = f"{NAME}/🔄 Transforms"
PRIMITIVES = f"{NAME}/🧱 Primitives"
MODELS_CAT = f"{NAME}/🤖 Models"
UTILS_CAT = f"{NAME}/🛠️ Utils"
FILE_CAT = f"{NAME}/📁 File"
LOGIC_CAT = f"{NAME}/🧠 Logic"

AUGMENTATION_CAT = f"{NAME}/Others/🔀 Augmentations"
PLATFROM_IO_CAT = f"{NAME}/Others/🔌 Platform IO"
DATA_CAT = f"{NAME}/Others/📊 Data"
LORA_CAT = f"{NAME}/Others/🧬 Loras"
